services:
  dixcord:
    container_name: dixcord
    image: dixcord/bot:latest
    build: .
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - ./data:/app/data
    working_dir: /app
    command: python -m src
